messages:
  usage: "&cUsage: %usage%"
  not-player: "&cOnly players can use that command!"
  no-hook: "&c%hook% hook was not found!"
  base-command-help:
    header: "&8&m----------&b&l%type% Help&8&m----------"
    body: "&b%usage% &8- &7%description%"
    footer: "&8&m--------------------"
  no-perms: "&cInsufficient permissions!"
  minigame:
    no-exist: "&cNo %game% game under the name '%name%' exists!"
    admin:
      exist: "&cA minigame under that name already exists!"
      reload: "&aSuccessfully reloaded %game%!"
      reload-all: "&aSuccessfully reloaded all minigames!"
      create: "&aSuccessfully created %game% game '%name%'!"
      delete: "&aSuccessfully deleted %game% game '%name%'!"
      start: "&aSuccessfully started %game% game '%name%'!"
      stop: "&aSuccessfully stopped %game% game '%name%'!"
      set-arena: "&aSuccessfully set the arena for %game% game '%name%'!"
      max-players: "&aSuccessfully set the maximum number of players allowed in '%name%' to %number%!"
      min-players: "&aSuccessfully set the minimum number of players required in '%name%' to %number%!"
      add-teleport: "%&aSuccessfully added teleport location to '%name%'!"
      remove-teleport: "%&aSuccessfully removed most recent teleport location from '%name%'!"
      clear-teleport: "%&aSuccessfully cleared all teleport locations from '%name%'!"
      no-teleport: "%cThere are no teleport locations to remove!"
      start-failed: "&cFailed to start game! Make sure it was setup properly."
      active: "&cThat game is already active!"
      not-active: "&cThat game is not active!"
      not-arena: "&cThat game does not support arenas!"
      no-selection: "&cNo selection found!"

minigame:
  database:
    # Can be either 'sqlite' or 'mysql'
    type: sqlite
    host:
    port:
    database:
    user:
    password: